project_id = "oybroifaleftwrhnlhqc"

[functions.instagram-oauth-callback]
verify_jwt = false

[functions.instagram-webhook]
verify_jwt = false

[functions.instagram-refresh-tokens]
verify_jwt = false
