project_id = "oybroifaleftwrhnlhqc"

[functions.admin-create-tenant]
verify_jwt = true

[functions.tenant-login]
verify_jwt = false

[functions.auto-transfer-contracted-to-posvenda]
verify_jwt = false
