// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/list-leads.ts
import { createClient } from "npm:@supabase/supabase-js@^2.99.1";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.25.76";
function supabaseForUser(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_leads_default = defineTool({
  name: "list_leads",
  title: "Listar leads",
  description: "Lista os leads do CRM aos quais o usu\xE1rio autenticado tem acesso. Suporta busca por nome/telefone e limite de resultados.",
  inputSchema: {
    search: z.string().optional().describe("Texto opcional para buscar em nome ou telefone do lead."),
    limit: z.number().int().min(1).max(100).default(20).describe("Quantidade m\xE1xima de leads a retornar (1-100).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ search, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado." }], isError: true };
    }
    const sb = supabaseForUser(ctx);
    let query = sb.from("crm_leads").select("id, name, phone, stage_id, pipeline_id, created_at, last_inbound_at, last_outbound_at").order("updated_at", { ascending: false }).limit(limit);
    if (search && search.trim()) {
      const sanitized = search.replace(/[\\"(),]/g, " ").trim();
      if (sanitized) {
        const term = `%${sanitized}%`;
        query = query.or(`name.ilike.${term},phone.ilike.${term}`);
      }
    }
    const { data, error } = await query;
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { leads: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-lead.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.99.1";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^3.25.76";
function supabaseForUser2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_lead_default = defineTool2({
  name: "get_lead",
  title: "Detalhes do lead",
  description: "Retorna os detalhes de um lead do CRM pelo ID, incluindo est\xE1gio, funil e \xFAltimos hor\xE1rios de mensagem.",
  inputSchema: {
    id: z2.string().uuid().describe("UUID do lead.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado." }], isError: true };
    }
    const sb = supabaseForUser2(ctx);
    const { data, error } = await sb.from("crm_leads").select("*").eq("id", id).maybeSingle();
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    if (!data) {
      return { content: [{ type: "text", text: "Lead n\xE3o encontrado." }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { lead: data }
    };
  }
});

// src/lib/mcp/tools/add-lead-note.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.99.1";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z3 } from "npm:zod@^3.25.76";
function supabaseForUser3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var add_lead_note_default = defineTool3({
  name: "add_lead_note",
  title: "Adicionar nota ao lead",
  description: "Adiciona uma nota interna a um lead do CRM. A nota fica vis\xEDvel para a equipe na conversa.",
  inputSchema: {
    lead_id: z3.string().uuid().describe("UUID do lead."),
    note: z3.string().trim().min(1).describe("Conte\xFAdo da nota.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ lead_id, note }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado." }], isError: true };
    }
    const sb = supabaseForUser3(ctx);
    const { data, error } = await sb.from("crm_conversation_notes").insert({ lead_id, content: note, author_id: ctx.getUserId() }).select().maybeSingle();
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: "Nota adicionada." }],
      structuredContent: { note: data }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "oybroifaleftwrhnlhqc";
var mcp_default = defineMcp({
  name: "rizodent-crm-mcp",
  title: "Rizodent CRM",
  version: "0.1.0",
  instructions: "Ferramentas para consultar e anotar leads do CRM Rizodent/CRClin. Use list_leads para descobrir leads, get_lead para detalhes e add_lead_note para registrar observa\xE7\xF5es internas. As opera\xE7\xF5es respeitam as permiss\xF5es do usu\xE1rio autenticado.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_leads_default, get_lead_default, add_lead_note_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
